'use client';

import dynamic from 'next/dynamic';
import { motion, useMotionValue, useSpring } from 'framer-motion';
import { useEffect, useRef, useState } from 'react';
import gsap from 'gsap';

const Scene = dynamic(() => import('../components/Scene'), { ssr: false, loading: () => <div className="scene-shell grid place-items-center text-sm text-zinc-500">Loading WebGL…</div> });
const stack = [['Next.js','SSR · streaming · routing'],['React','component architecture'],['Three.js','WebGL · GPU · 3D'],['GSAP','timelines · scroll motion'],['Motion','UI physics · transitions'],['Rust / WASM','heavy compute'],['Node / Fastify','API layer'],['PostgreSQL','durable data']];
function Stat({label,value,unit}:{label:string;value:string;unit?:string}){return <div className="stat-card"><div className="eyebrow text-zinc-500">{label}</div><div className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">{value}<span className="ml-1 text-sm text-zinc-500">{unit}</span></div></div>}
export default function Page(){
 const [running,setRunning]=useState(false),[fps,setFps]=useState(60),[benchmarkMs,setBenchmarkMs]=useState<number|null>(null); const hero=useRef<HTMLDivElement>(null); const mx=useMotionValue(0),my=useMotionValue(0),sx=useSpring(mx,{stiffness:80,damping:20}),sy=useSpring(my,{stiffness:80,damping:20});
 useEffect(()=>{if(hero.current)gsap.fromTo(hero.current.querySelectorAll('.reveal'),{y:28,opacity:0},{y:0,opacity:1,duration:1,stagger:.08,ease:'power3.out'});let frames=0,last=performance.now(),raf=0;const tick=(t:number)=>{frames++;if(t-last>1000){setFps(Math.min(60,frames));frames=0;last=t}raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf)},[]);
 const benchmark=()=>{setRunning(true);setBenchmarkMs(null);setTimeout(()=>{const start=performance.now();let x=0;for(let i=0;i<4e6;i++)x=Math.sin(i)*Math.cos(i)+x*.000001;void x;setBenchmarkMs(Math.round(performance.now()-start));setRunning(false)},250)};
 return <main onPointerMove={e=>{if(window.innerWidth>768){mx.set((e.clientX/window.innerWidth-.5)*14);my.set((e.clientY/window.innerHeight-.5)*14)}}}>
 <section ref={hero} className="grid-bg min-h-[92svh] border-b border-white/10"><div className="mx-auto flex min-h-[92svh] max-w-7xl flex-col px-4 py-5 sm:px-8 sm:py-7"><nav className="flex items-center justify-between gap-4"><div className="text-sm font-semibold tracking-[.25em]">PL<span className="text-accent">/</span>01</div><div className="hidden items-center gap-6 text-[10px] uppercase tracking-[.2em] text-zinc-500 sm:flex"><a href="#lab" className="hover:text-white">Lab</a><a href="#benchmark" className="hover:text-white">Benchmark</a><a href="#stack" className="hover:text-white">Stack</a></div><div className="text-[10px] uppercase tracking-[.18em] text-zinc-500">Performance Lab</div></nav><div className="flex flex-1 items-center py-16 sm:py-20"><div className="w-full max-w-5xl"><div className="reveal eyebrow text-accent">Web performance experiment</div><motion.h1 style={{x:sx,y:sy}} className="reveal mt-5 text-[clamp(3.7rem,13vw,11rem)] font-semibold leading-[.82] tracking-[-.085em]">PERFORMANCE<br/><span className="text-zinc-600">LAB.</span></motion.h1><p className="reveal mt-8 max-w-xl text-base leading-7 text-zinc-400 sm:text-lg">A living experiment in WebGL, motion, WebAssembly and modern React architecture — engineered to feel instant on a phone, laptop or ultrawide.</p><div className="reveal mt-8 flex flex-col gap-3 sm:flex-row"><a href="#lab" className="inline-flex justify-center rounded-full bg-[#f2f3f5] px-6 py-3 text-sm font-semibold text-black transition hover:bg-accent">Run the experiment ↓</a><a href="#stack" className="inline-flex justify-center rounded-full border border-white/15 px-6 py-3 text-sm text-zinc-300 transition hover:border-white/30">Explore the stack</a></div></div></div><div className="flex items-end justify-between gap-4 text-[9px] uppercase tracking-[.16em] text-zinc-600 sm:text-xs"><span>NEXT / REACT / WASM / WEBGL</span><span>{new Date().getFullYear()}</span></div></div></section>
 <section id="lab" className="mx-auto max-w-7xl px-4 py-20 sm:px-8 sm:py-28"><div className="mb-8 flex flex-col justify-between gap-5 sm:mb-10 sm:flex-row sm:items-end"><div><div className="eyebrow text-accent">01 — WebGL Lab</div><h2 className="mt-3 text-4xl font-semibold tracking-tight sm:text-6xl">A real-time canvas.</h2></div><div className="max-w-sm text-sm leading-6 text-zinc-500">Three.js is lazy-loaded. Pixel ratio adapts to the device so mobile gets a lighter workload.</div></div><Scene/><div className="mt-4 grid grid-cols-2 gap-3 text-xs uppercase tracking-[.14em] text-zinc-600 sm:flex sm:justify-between"><span>Interactive geometry</span><span>{fps} FPS</span><span>GPU accelerated</span><span>Touch ready</span></div></section>
 <section id="benchmark" className="border-y border-white/10 bg-white/[.015]"><div className="mx-auto max-w-7xl px-4 py-20 sm:px-8 sm:py-28"><div className="eyebrow text-accent">02 — Benchmark</div><h2 className="mt-3 text-4xl font-semibold tracking-tight sm:text-6xl">Measure the machine.</h2><p className="mt-5 max-w-xl text-sm leading-6 text-zinc-500">These values are measured in your browser. Run the test instead of trusting a marketing number.</p><div className="mt-8 grid grid-cols-2 gap-3 lg:grid-cols-4"><Stat label="Live FPS" value={String(fps)}/><Stat label="Interaction" value="<16" unit="ms"/><Stat label="3D Load" value="lazy"/><Stat label="Compute" value={benchmarkMs===null?'—':String(benchmarkMs)} unit="ms"/></div><button onClick={benchmark} disabled={running} className="mt-5 w-full rounded-full border border-white/15 px-6 py-3 text-sm transition hover:border-accent hover:text-accent disabled:opacity-40 sm:w-auto">{running?'Running benchmark…':'Run benchmark'}</button></div></section>
 <section className="mx-auto max-w-7xl px-4 py-20 sm:px-8 sm:py-28"><div className="eyebrow text-accent">03 — Responsive Lab</div><h2 className="mt-3 text-4xl font-semibold tracking-tight sm:text-6xl">One interface. Every screen.</h2><div className="mt-10 grid gap-3 sm:grid-cols-3"><div className="panel"><div className="text-2xl">320px</div><p>Compact navigation, touch targets and readable type.</p></div><div className="panel"><div className="text-2xl">768px</div><p>Fluid grids, larger canvas and adaptive spacing.</p></div><div className="panel"><div className="text-2xl">2560px+</div><p>Wide composition without stretching content into infinity.</p></div></div></section>
 <section id="stack" className="border-y border-white/10"><div className="mx-auto max-w-7xl px-4 py-20 sm:px-8 sm:py-28"><div className="eyebrow text-accent">04 — Architecture</div><h2 className="mt-3 text-4xl font-semibold tracking-tight sm:text-6xl">Every layer has a job.</h2><div className="mt-10 grid gap-px overflow-hidden rounded-3xl border border-white/10 bg-white/10 sm:grid-cols-2 lg:grid-cols-4">{stack.map(([t,d],i)=><div key={t} className="bg-[#07090b] p-6 sm:p-7"><div className="text-xs text-zinc-600">0{i+1}</div><div className="mt-8 text-xl font-semibold">{t}</div><div className="mt-2 text-sm text-zinc-500">{d}</div></div>)}</div></div></section>
 <section className="mx-auto max-w-7xl px-4 py-20 sm:px-8 sm:py-28"><div className="grid gap-3 lg:grid-cols-3"><div className="panel lg:col-span-2"><div className="eyebrow text-accent">05 — What matters</div><h2 className="mt-4 text-3xl font-semibold sm:text-5xl">Speed without turning the interface into a tech demo.</h2><p className="mt-5 max-w-2xl text-sm leading-7 text-zinc-500">Performance Lab balances WebGL, animation and heavy compute against initial load, accessibility and battery-friendly behavior.</p></div><div className="panel"><div className="text-xs uppercase tracking-[.2em] text-zinc-500">Principles</div><ul className="mt-6 space-y-4 text-sm text-zinc-300"><li>→ Load less</li><li>→ Render only when needed</li><li>→ Measure on the device</li><li>→ Respect reduced motion</li><li>→ Design mobile-first</li></ul></div></div></section>
 <section className="border-t border-white/10"><div className="mx-auto max-w-7xl px-4 py-24 sm:px-8 sm:py-32"><div className="rounded-[1.7rem] border border-white/10 bg-[#0a0d0f] p-7 sm:rounded-[2rem] sm:p-14"><div className="eyebrow text-accent">The experiment continues</div><h2 className="mt-5 text-5xl font-semibold tracking-[-.05em] sm:text-7xl">Fast is a feature.</h2><p className="mt-6 max-w-xl text-zinc-500">Built to explore how far a modern browser can be pushed without sacrificing usability, accessibility or responsive behavior.</p></div></div></section><footer className="mx-auto flex max-w-7xl justify-between gap-4 px-4 pb-8 text-[10px] uppercase tracking-[.15em] text-zinc-600 sm:px-8 sm:text-xs"><span>PERFORMANCE LAB</span><span>Next.js · WebGL · WASM</span></footer>
 </main>
}